version: '3.8'
services:
  flask_app:
    build: ./flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/usr/src/app
#      - ./flask_app/videos:/usr/src/app/videos
#      - ./flask_app/processed_videos:/usr/src/app/processed_videos
#      - ./flask_app/static:/usr/src/app/static
#      - ./flask_app/static/processed:/usr/src/app/static/processed
      - ./video_processor/mmtracking:/usr/src/app/mmtracking
      - ./video_processor/mmdetection:/usr/src/app/mmdetection
    depends_on:
      - video_processor
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/video_db

  video_processor:
    build: ./video_processor
    volumes:
      - ./flask_app/videos:/usr/src/app/videos
      - ./flask_app/processed_videos:/usr/src/app/processed_videos
      - ./flask_app/static:/usr/src/app/static
      - ./flask_app/static/processed:/usr/src/app/static/processed
      - ./video_processor/mmtracking:/usr/src/app/mmtracking
      - ./video_processor/mmdetection:/usr/src/app/mmdetection
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/video_db
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]
            driver: nvidia
            count: all

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
